# Site settings
title:       Semicolon
author:      Nikhil Mopidevi
description: "The place where I speak code."
baseurl:     "" 
url:         "" 

# Social Links
email:            nikhilkumarmopidevi@gmail.com
twitter_username: nikhilmopidevi
github_username:  nikhilmopidevi

# Build settings
markdown: kramdown
permalink: pretty

# Google Services
google_analytics: UA-77180736-1

